---
- hosts: all
  become: yes

  tasks:
  - name: Install all necessary on debian based distros
    apt:
      name:
        - vim
        - curl
        - wget
        - build-essential
        - libssl-dev
        - python3
        - python3-pip
        - apache2
        
      state: present
      update_cache: true

  - name: Copy file with owner and permissions
    copy:
      src: index.html
      dest: /var/www/html/index.html
      owner: root

  - name: ensure apache service is running
    service: 
      name: apache2
      state: started
      enabled: true
 
       
    # when: ansible_os_family == 'Debian'